# -*- coding: utf-8 -*-
"""variables_and_ data_types.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M-WPrLGP7yo0_fv5oOtpod5VpH88h5Uz
"""

# Day 1 & 2: 30 Days of Python Programming

# Exercises: Level 1

# Variables

first_name = 'Emmanuel'
last_name = 'Salako'
full_name = 'Emmanuel Salako'
country= 'Nigeria'
city = 'Abuja'
age = 23
year = 2026
is_married = False
is_True = 'I am enjouing 30 Days of Python Programming'
is_light_on = True

# Multiple Variable

first_name, last_name, full_name, country, city, age, year = 'Emmanuel', 'Salako', 'Emmmanuel Salako', 'Nigeria', 'Abuja', 23, 2026

# Exercises: Level 2

# Checking the data types of all my varibales

print(type(first_name))             # str
print(type(last_name))              # str
print(type(full_name))              # str
print(type(country))                # str
print(type(city))                   # str
print(type(age))                    # int
print(type(year))                   # int
print(type(is_married))             # bool
print(type(is_True))                # str
print(type(is_light_on))            # bool

# Using the len() built-in function to find the length the length of my first name

print(len(first_name))              # 8

# Comparing the lenght of my first name and last name

print(len(first_name)) == print(len(last_name))

# Declaring 5 as num_one and 4 as num_two

num_one = 5
num_two = 4

# Adding num_one and num_two and assign the value to a variable total

variable_total = num_one + num_two
print(variable_total)

# Subtracting num_two from num_one and assign the value to a varibale diff

variable_diff = num_one - num_two
print(variable_diff)

# Multiplying num_two and num_one and assign the value to a variable product

variable_product = num_one * num_two
print(variable_product)

# Divide num_one by num_two and assign the value to a variable division

variable_division = num_one / num_two
print(variable_division)

# Using modulus division to find num_two divided by num_one and assign the value to a variable remainder

variable_division = num_one % num_two
print(variable_division)

# Calculating num_one to the power of num_two and assign the value to a varibale exp

variable_exp = num_one ** num_two
print(variable_exp)

# Finding the floor divison of num_one by num_two and assign the value to a vairibale floor_division

variable_floor_division = num_one // num_two
print(variable_floor_division)

# Calculating the area of a circle and assign the value to a vairable name of area_of_circle

radius = 30
pi = 3.4
area_of_circle = pi * radius ** 2
print(area_of_circle)

# Calculating the circumference of a circle and assign the value to a variable name of circum_of_circle

circum_of_circle = 2 * pi * radius
print(circum_of_circle)

# Taking radius as user input and calculate the area

radius = float(input('What is the radius of the circle?'))
area_of_circle = pi * radius ** 2
print(area_of_circle)

# Using the input() built-in function to get first name, last name, country, and age ...

first_name = input('What is your first name?')
last_name = input('What is your last name?')
country = input('What is your country?')
age = input('What is your age?')

print(first_name)
print(last_name)
print(country)
print(age)

# Checking for the Python reserved words or keywords

help('keywords')